refactor: [ANDROSDK-1712] replace rxjava login call
dhis2/dhis2-android-sdk pull request #2001
Opened 2023-08-10 10:44 UTC by dan-dhis2

fix:
- LogInCallUnitShould.kt to handle the refactor
- CoroutineAPICallExecutorMock.kt now it handles D2Error gently
- 
refactor: to coroutines
- UserModuleImpl.kt
- UserCall.kt
- LogInCall.kt
- some isolated calls to the new coroutines functions
- UserService.kt to remove retrofit's "Call"
- OpenIDConnectHandlerImpl.kt
- rxjava from LogInCallUnitShould.kt
- UserCallShould.kt

2023-09-04 08:30 UTC, vgarciabnz requested changes

2023-09-04 08:30 UTC, vgarciabnz commented on core/src/main/java/org/hisp/dhis/android/core/user/internal/LogInCall.kt
> +            val user = coroutineAPICallExecutor.wrap {
The `apiCallErrorCatcher` is removed. It must be passed as a parameter to the `wrap` function.

2023-09-04 08:30 UTC, vgarciabnz commented on core/src/main/java/org/hisp/dhis/android/core/user/internal/LogInCall.kt
> +            val user = coroutineAPICallExecutor.wrap { authenticateCall }.getOrThrow()
The `authenticateCall`is executed at the time it is declared. Before, it was a `Callable` so it was executed when its method `call` was invoked; but now it is a suspend function.
The actual invokation must be wrapped by the `wrap` function.

2023-09-04 08:30 UTC, vgarciabnz commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip
Why this downgrade?

2023-09-05 11:52 UTC, vgarciabnz requested changes

2023-09-05 11:52 UTC, vgarciabnz commented on core/src/main/java/org/hisp/dhis/android/core/user/internal/LogInCall.kt
> +            val user = coroutineAPICallExecutor.wrap {
The `apiCallErrorCatcher` is missing

2023-09-05 13:14 UTC, dan-dhis2 commented on core/src/main/java/org/hisp/dhis/android/core/user/internal/LogInCall.kt
> +            val user = coroutineAPICallExecutor.wrap {
Done!

2023-09-06 08:04 UTC, vgarciabnz approved these changes

2023-09-06 08:04 UTC, merged