(experimental) refactor: [ANDROSDK-1720] refactor Call classes to Kotlin
dhis2/dhis2-android-sdk pull request #2020
Opened 2023-09-13 09:43 UTC by dan-dhis2

From PR [2019](https://github.com/dhis2/dhis2-android-sdk/pull/2019)

_Refactor the following

UidsCall
QueryCall
ListCall
ObjectCall
And their implementations, to Kotlin_

2023-09-14 06:08 UTC, vgarciabnz requested changes
It looks good. Two general comments that can be done in the next PR:
- Remove "java.lang.Boolean" dependencies. They were added in the conversion to Kotlin and should be replaced by native Kotlin boolean.
- Most of the call classes can be internal

2023-09-15 12:17 UTC, dan-dhis2 commented on core/src/main/java/org/hisp/dhis/android/core/program/internal/ProgramCall.kt
> +    private val handler: Handler<Program>
To be included in RxJava refactor in MetadataCall [Jira Issue ANDROSDK-1683](https://dhis2.atlassian.net/browse/ANDROSDK-1683)

2023-09-15 12:17 UTC, dan-dhis2 commented on core/src/main/java/org/hisp/dhis/android/core/event/internal/EventFilterCall.kt
> +class EventFilterCall @Inject internal constructor(
To be included in RxJava refactor in MetadataCall [Jira Issue ANDROSDK-1683](https://dhis2.atlassian.net/browse/ANDROSDK-1683)

2023-09-15 12:17 UTC, dan-dhis2 commented on core/src/main/java/org/hisp/dhis/android/core/event/internal/EventFilterCall.kt
> +    private val handler: Handler<EventFilter>
To be included in RxJava refactor in MetadataCall [Jira Issue ANDROSDK-1683](https://dhis2.atlassian.net/browse/ANDROSDK-1683)

2023-09-15 12:18 UTC, dan-dhis2 commented
To be closed by @vgarciabnz 
As all requested changes will be included in RxJava refactor in MetadataCall [Jira Issue ANDROSDK-1683](https://dhis2.atlassian.net/browse/ANDROSDK-1683)

2023-09-21 10:57 UTC, vgarciabnz approved these changes

2023-09-21 10:58 UTC, merged