feat: [ANDROSDK-1908] Add property displayContent in programRuleAction
dhis2/dhis2-android-sdk pull request #2210
Opened 2024-08-22 08:00 UTC by taridepaco

Related task: [ANDROSDK-1908](https://dhis2.atlassian.net/jira/software/c/projects/ANDROSDK/boards/93?selectedIssue=ANDROSDK-1908)

2024-08-22 08:36 UTC, andresmr approved these changes

2024-08-22 11:39 UTC, vgarciabnz requested changes
There is a missing change in a test `ProgramRuleActionShould`. It is already implicitly tested in the integration test, but still good to have it as a separate unit test.

2024-08-22 11:42 UTC, vgarciabnz commented
This PR adds a new property, which makes the app change from `content` to `displayContent` @andresmr . The alternative would be deprecate `content` and fallback to `displayContent` value, as we did for the labels in program and programStage. What do you think is the best approach? Keeping both properties is more verbose but maybe more consistent with the rest of the code.

2024-08-23 07:01 UTC, vgarciabnz approved these changes

2024-08-26 12:13 UTC, taridepaco commented
This property was added in version 2.33.

2024-08-27 07:43 UTC, merged