chore: [ANDROSDK-1867] use non deprecated ping endpoint
dhis2/dhis2-android-sdk pull request #2219
Opened 2024-09-03 11:55 UTC by taridepaco

Related task: [ANDROSDK-1867](https://dhis2.atlassian.net/jira/software/c/projects/ANDROSDK/boards/93?selectedIssue=ANDROSDK-1867)

2024-09-04 05:56 UTC, vgarciabnz requested changes
The endpoint `/api/ping` is not available in older versions. Checking the backend code, it seems that it is not available in version 2.36 and below.
If you want to keep compatibility with older versions, we would need to make this request dependent on the version.

2024-09-04 10:18 UTC, andresmr approved these changes

2024-09-05 11:55 UTC, taridepaco commented
After setting up a local server with version 36, I could successfully perform a ping to the server.

2024-09-05 11:55 UTC, vgarciabnz approved these changes

2024-09-05 13:08 UTC, merged